"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:10:03.737632
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_orders',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('release_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('service_name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=64), nullable=False),
    sa.Column('env_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_orders_env_id'), 'release_orders', ['env_id'], unique=False)
    op.create_index(op.f('ix_release_orders_release_no'), 'release_orders', ['release_no'], unique=True)
    op.create_index(op.f('ix_release_orders_service_name'), 'release_orders', ['service_name'], unique=False)
    op.create_index(op.f('ix_release_orders_status'), 'release_orders', ['status'], unique=False)
    op.create_index(op.f('ix_release_orders_title'), 'release_orders', ['title'], unique=False)
    op.create_table('rollback_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('release_order_id', sa.String(length=64), nullable=False),
    sa.Column('release_no', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('target_version', sa.String(length=64), nullable=False),
    sa.Column('operator', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rollback_records_release_no'), 'rollback_records', ['release_no'], unique=False)
    op.create_index(op.f('ix_rollback_records_release_order_id'), 'rollback_records', ['release_order_id'], unique=False)
    op.create_index(op.f('ix_rollback_records_status'), 'rollback_records', ['status'], unique=False)
    op.create_table('target_environments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('cluster', sa.String(length=128), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_target_environments_name'), 'target_environments', ['name'], unique=True)
    op.create_index(op.f('ix_target_environments_status'), 'target_environments', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_target_environments_status'), table_name='target_environments')
    op.drop_index(op.f('ix_target_environments_name'), table_name='target_environments')
    op.drop_table('target_environments')
    op.drop_index(op.f('ix_rollback_records_status'), table_name='rollback_records')
    op.drop_index(op.f('ix_rollback_records_release_order_id'), table_name='rollback_records')
    op.drop_index(op.f('ix_rollback_records_release_no'), table_name='rollback_records')
    op.drop_table('rollback_records')
    op.drop_index(op.f('ix_release_orders_title'), table_name='release_orders')
    op.drop_index(op.f('ix_release_orders_status'), table_name='release_orders')
    op.drop_index(op.f('ix_release_orders_service_name'), table_name='release_orders')
    op.drop_index(op.f('ix_release_orders_release_no'), table_name='release_orders')
    op.drop_index(op.f('ix_release_orders_env_id'), table_name='release_orders')
    op.drop_table('release_orders')
    # ### end Alembic commands ###
